title: "Lotrives"
description: "Una mirada al mundo que somos"

author: "José Manuel Grau Navarro"

lang: "es"
timezone: "Europe/Madrid"

theme: minima

url: "https://lotrives.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

google_analytics: G-BT8CB5X306

header_pages:
  - acerca.md
  - archivo.md
  - etiquetas.md
  - buscar.md
  - newsletter.md

minima:
  social_links:
    - title: "X (Twitter)"
      icon: x-twitter
      url: "https://x.com/jmgraunavarro"
    - title: "GitHub"
      icon: github
      url: "https://github.com/lotrives"

twitter_username: "jmgraunavarro"
github_username: "lotrives"

sass:
  style: compressed
